import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <nav className="w-full bg-[#4E76ED]  flex justify-center items-center h-16">
          <a className="text-white text-xl">QuickKit</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
