import type { Metadata } from "next";
import { Oswald, Pacifico } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  weight: "400"
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F8F8FF] ${oswald.className}`}>
        <div className="p-4">
          <nav className="w-full rounded-xl drop-shadow-xl bg-[#4E76ED] flex justify-center items-center h-16">
            <a className={`text-white text-xl  ${pacifico.className}`}>QuickKit</a>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
